name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNOWPACK_SERVER: ${{ secrets.SNOWPACK_SERVER }}
  SNOWPACK_PRIV_KEY: ${{ secrets.SNOWPACK_PRIV_KEY }}
  SNOWPACK_PRIV_KEY_FILE: /tmp/rsa_key.p8
  SNOWPACK_DRIVER: /home/runner/work/snowpack/snowpack/snowflake_odbc/lib/libSnowflake.so

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.12'
              otp: 24
              driver: '2.24.7'
            lint: lint
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install iODBC
        run: |
          sudo apt-get update
          sudo apt-get install libiodbc2 iodbc

      - name: Install Snowflake Driver
        run: |
          curl --output snowflake_linux_x8664_odbc-${{matrix.pair.driver}}.tgz \
            https://sfc-repo.snowflakecomputing.com/odbc/linux/${{matrix.pair.driver}}/snowflake_linux_x8664_odbc-${{matrix.pair.driver}}.tgz \

          gunzip snowflake_linux_x8664_odbc-${{matrix.pair.driver}}.tgz
          tar -xvf snowflake_linux_x8664_odbc-${{matrix.pair.driver}}.tar

          cd snowflake_odbc
          sudo ./iodbc_setup.sh

      - name: Put Private Key in File
        run: |
          echo "${{ secrets.SNOWPACK_PRIV_KEY }}" >> /tmp/rsa_key.p8

      - uses: actions/cache@v2
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix credo --strict
        if: ${{ matrix.lint }}

      - run: mix test --exclude ciskip:true
        if: ${{ ! matrix.lint }}

      - run: mix test --exclude ciskip:true --warnings-as-errors
        if: ${{ matrix.lint }}

  semantic_release:
    name: Semantic Release
    needs: test
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      last_release_version: ${{ steps.semantic.outputs.last_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Semantic Release
        id: semantic
        uses: hgdata/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extends: |
            @hgdata/semantic-release-config


